export const rows: Array<any> = [
  { id: 1,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQDQpJSvlQaulIYwuzlLop3qpJ-MEBvSbIGg&usqp=CAU',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
  { id: 2,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQDQpJSvlQaulIYwuzlLop3qpJ-MEBvSbIGg&usqp=CAU',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
  { id: 3,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQDQpJSvlQaulIYwuzlLop3qpJ-MEBvSbIGg&usqp=CAU',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
  { id: 4,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQDQpJSvlQaulIYwuzlLop3qpJ-MEBvSbIGg&usqp=CAU',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
  { id: 5,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQDQpJSvlQaulIYwuzlLop3qpJ-MEBvSbIGg&usqp=CAU',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
  { id: 6,
    avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQDQpJSvlQaulIYwuzlLop3qpJ-MEBvSbIGg&usqp=CAU',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
  { id: 7,
    avatar: 'https://i0.wp.com/smsforwishes.com/wp-content/uploads/2022/03/d3a875fe0d936e862a92013c7b985cb7.jpeg?resize=700%2C875&ssl=1',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
  { id: 8,
    avatar: 'https://i0.wp.com/smsforwishes.com/wp-content/uploads/2022/03/d3a875fe0d936e862a92013c7b985cb7.jpeg?resize=700%2C875&ssl=1',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
  { id: 9,
    avatar: 'https://i0.wp.com/smsforwishes.com/wp-content/uploads/2022/03/d3a875fe0d936e862a92013c7b985cb7.jpeg?resize=700%2C875&ssl=1',
    user: 'Monica Bellucci',
    email: 'jon@mail.com',
    status: 'active',
    transaction: '$120.00'
  },
];